package GUI;

import HotelRelated.MemberType;
import Nonhotel.Host;

import javax.swing.*;
import java.sql.Connection;
import java.time.LocalDate;

import static DB.JavaDataBase.*;

/**
 *
 * @author DOOMSLAYER
 */
public class GuestAdd extends javax.swing.JFrame {

    /**
     * Creates new form GuestAdd
     */
    public GuestAdd(Host host) {
        setHost(host);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        CheckInLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CheckInPane = new javax.swing.JTextPane();
        jSeparator1 = new javax.swing.JSeparator();
        CheckOutLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        CheckOutPane = new javax.swing.JTextPane();
        RMlabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        RoomIDpane = new javax.swing.JTextPane();
        ReservationLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        reservationPANE = new javax.swing.JTextPane();
        TypeLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        AddButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        MemberType = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invitado");
        setBackground(new java.awt.Color(153, 153, 153));

        NameLabel.setText("Nombre");

        CheckInLabel.setText("Checkin");

        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        CheckInPane.setEditable(false);
        CheckInPane.setText(host.getEntrydate().toString());
        jScrollPane1.setViewportView(CheckInPane);

        CheckOutLabel.setText("CheckOut");

        CheckOutPane.setEditable(false);
        CheckOutPane.setText(host.getExitdate().toString());
        jScrollPane2.setViewportView(CheckOutPane);

        RMlabel.setText("NumCuarto");

        RoomIDpane.setEditable(false);
        RoomIDpane.setText(Integer.toString(host.getROOM()));
        jScrollPane3.setViewportView(RoomIDpane);

        ReservationLabel.setText("Id_Reserva");

        reservationPANE.setEditable(false);
        reservationPANE.setText(Integer.toString(host.getreservationID()));
        jScrollPane4.setViewportView(reservationPANE);

        TypeLabel.setText("Tipo ");

        AddButton.setBackground(new java.awt.Color(102, 153, 255));
        AddButton.setText("Añadir invitado");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancelar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        MemberType.setModel(new javax.swing.DefaultComboBoxModel<>(HotelRelated.MemberType.values()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(RMlabel)
                                                                        .addComponent(ReservationLabel)
                                                                        .addComponent(TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(MemberType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addComponent(CheckOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(jScrollPane2))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addComponent(CheckInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(0, 14, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jSeparator1))))
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(CancelButton)
                                .addGap(18, 18, 18)
                                .addComponent(AddButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NameLabel)
                                        .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TypeLabel)
                                        .addComponent(MemberType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RMlabel)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReservationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckInLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CheckOutLabel)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddButton)
                                        .addComponent(CancelButton))
                                .addGap(56, 56, 56))
        );

        pack();
        setVisible(true);
    }// </editor-fold>

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(NameTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Se necesita un nombre", "Nombre invalido", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            host.setNombre(NameTextField.getText());
            host.setMembershiptype(MemberType.getSelectedItem().toString());
            System.out.println(host);
            try
            {
                Connection connection = getConnection();
                Add_Guest(connection, host);
                JOptionPane.showMessageDialog(null, "Huesped añadido :)");
                int capacity = getcapacityAvailable(host.getreservationID());
                reduceCapacity(connection, host.getreservationID(), capacity-1);
                dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error en base de datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        dispose();
    }

    public void setHost(Host host) {
        this.host = host;
    }

    private Host host;


    // Variables declaration - do not modify
    private javax.swing.JButton AddButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CheckInLabel;
    private javax.swing.JTextPane CheckInPane;
    private javax.swing.JLabel CheckOutLabel;
    private javax.swing.JTextPane CheckOutPane;
    private javax.swing.JComboBox<HotelRelated.MemberType> MemberType;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel RMlabel;
    private javax.swing.JLabel ReservationLabel;
    private javax.swing.JTextPane RoomIDpane;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextPane reservationPANE;
    // End of variables declaration
}
