package GUI;

import Nonhotel.RoomChecker;




import java.awt.Color;

/**
 *
 * @author DOOMSLAYER
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        EmpleadosLabelbutton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ReservacionesLabelbutton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AtencionClienteLabelButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BuscarLabelButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        AddGuestsButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CheckRoomsLabelbutton = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        EmpleadosLabelbutton.setToolTipText("");
        EmpleadosLabelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmpleadosLabelbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EmpleadosLabelbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EmpleadosLabelbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmpleadosLabelbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                EmpleadosLabelbuttonMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Empleados");

        javax.swing.GroupLayout EmpleadosLabelbuttonLayout = new javax.swing.GroupLayout(EmpleadosLabelbutton);
        EmpleadosLabelbutton.setLayout(EmpleadosLabelbuttonLayout);
        EmpleadosLabelbuttonLayout.setHorizontalGroup(
                EmpleadosLabelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmpleadosLabelbuttonLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmpleadosLabelbuttonLayout.setVerticalGroup(
                EmpleadosLabelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EmpleadosLabelbuttonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        ReservacionesLabelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservacionesLabelbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReservacionesLabelbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReservacionesLabelbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReservacionesLabelbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ReservacionesLabelbuttonMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reservaciones");

        javax.swing.GroupLayout ReservacionesLabelbuttonLayout = new javax.swing.GroupLayout(ReservacionesLabelbutton);
        ReservacionesLabelbutton.setLayout(ReservacionesLabelbuttonLayout);
        ReservacionesLabelbuttonLayout.setHorizontalGroup(
                ReservacionesLabelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ReservacionesLabelbuttonLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReservacionesLabelbuttonLayout.setVerticalGroup(
                ReservacionesLabelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ReservacionesLabelbuttonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        AtencionClienteLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtencionClienteLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AtencionClienteLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AtencionClienteLabelButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtencionClienteLabelButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AtencionClienteLabelButtonMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Atencion a Cliente");

        javax.swing.GroupLayout AtencionClienteLabelButtonLayout = new javax.swing.GroupLayout(AtencionClienteLabelButton);
        AtencionClienteLabelButton.setLayout(AtencionClienteLabelButtonLayout);
        AtencionClienteLabelButtonLayout.setHorizontalGroup(
                AtencionClienteLabelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AtencionClienteLabelButtonLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AtencionClienteLabelButtonLayout.setVerticalGroup(
                AtencionClienteLabelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AtencionClienteLabelButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        BuscarLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarLabelButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BuscarLabelButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BuscarLabelButtonMouseReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Buscar");

        javax.swing.GroupLayout BuscarLabelButtonLayout = new javax.swing.GroupLayout(BuscarLabelButton);
        BuscarLabelButton.setLayout(BuscarLabelButtonLayout);
        BuscarLabelButtonLayout.setHorizontalGroup(
                BuscarLabelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BuscarLabelButtonLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BuscarLabelButtonLayout.setVerticalGroup(
                BuscarLabelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BuscarLabelButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        AddGuestsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddGuestsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddGuestsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddGuestsButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddGuestsButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AddGuestsButtonMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Checar reservaciones");

        javax.swing.GroupLayout AddGuestsButtonLayout = new javax.swing.GroupLayout(AddGuestsButton);
        AddGuestsButton.setLayout(AddGuestsButtonLayout);
        AddGuestsButtonLayout.setHorizontalGroup(
                AddGuestsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddGuestsButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddGuestsButtonLayout.setVerticalGroup(
                AddGuestsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddGuestsButtonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        CheckRoomsLabelbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckRoomsLabelbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckRoomsLabelbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckRoomsLabelbuttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckRoomsLabelbuttonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CheckRoomsLabelbuttonMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Consultar Cuartos");

        javax.swing.GroupLayout CheckRoomsLabelbuttonLayout = new javax.swing.GroupLayout(CheckRoomsLabelbutton);
        CheckRoomsLabelbutton.setLayout(CheckRoomsLabelbuttonLayout);
        CheckRoomsLabelbuttonLayout.setHorizontalGroup(
                CheckRoomsLabelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CheckRoomsLabelbuttonLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckRoomsLabelbuttonLayout.setVerticalGroup(
                CheckRoomsLabelbuttonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(CheckRoomsLabelbuttonLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EmpleadosLabelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ReservacionesLabelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AtencionClienteLabelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BuscarLabelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(AddGuestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(CheckRoomsLabelbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EmpleadosLabelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ReservacionesLabelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AtencionClienteLabelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BuscarLabelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddGuestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckRoomsLabelbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/istockphoto-472899538-612x612.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void EmpleadosLabelbuttonMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        EmpleadosLabelbutton.setBackground(new Color(112,128,144));
    }

    private void ReservacionesLabelbuttonMousePressed(java.awt.event.MouseEvent evt) {
        ReservacionesLabelbutton.setBackground(new Color(112,128,144));
    }

    private void AtencionClienteLabelButtonMousePressed(java.awt.event.MouseEvent evt) {
        AtencionClienteLabelButton.setBackground(new Color(112,128,144));
    }

    private void ReservacionesLabelbuttonMouseEntered(java.awt.event.MouseEvent evt) {
        ReservacionesLabelbutton.setBackground(new Color(112,128,144));
    }

    private void AtencionClienteLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {
        AtencionClienteLabelButton.setBackground(new Color(112,128,144));
    }

    private void EmpleadosLabelbuttonMouseEntered(java.awt.event.MouseEvent evt) {
        EmpleadosLabelbutton.setBackground(new Color(112,128,144));
    }

    private void EmpleadosLabelbuttonMouseReleased(java.awt.event.MouseEvent evt) {
        EmpleadosLabelbutton.setBackground(new Color(112,128,144));
    }

    private void EmpleadosLabelbuttonMouseExited(java.awt.event.MouseEvent evt) {
        EmpleadosLabelbutton.setBackground(new Color(60,63,65));

    }

    private void ReservacionesLabelbuttonMouseExited(java.awt.event.MouseEvent evt) {
        ReservacionesLabelbutton.setBackground(new Color(60,63,65));
    }

    private void ReservacionesLabelbuttonMouseReleased(java.awt.event.MouseEvent evt) {
        ReservacionesLabelbutton.setBackground(new Color(112,128,144));
    }

    private void AtencionClienteLabelButtonMouseExited(java.awt.event.MouseEvent evt) {
        AtencionClienteLabelButton.setBackground(new Color(60,63,65));
    }

    private void AtencionClienteLabelButtonMouseReleased(java.awt.event.MouseEvent evt) {
        AtencionClienteLabelButton.setBackground(new Color(112,128,144));
    }

    private void BuscarLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        BuscarLabelButton.setBackground(new Color(112,128,144));

    }

    private void BuscarLabelButtonMouseExited(java.awt.event.MouseEvent evt) {
        BuscarLabelButton.setBackground(new Color(60,63,65));
    }

    private void BuscarLabelButtonMousePressed(java.awt.event.MouseEvent evt) {
        BuscarLabelButton.setBackground(new Color(112,128,144));
    }

    private void BuscarLabelButtonMouseReleased(java.awt.event.MouseEvent evt) {
        BuscarLabelButton.setBackground(new Color(112,128,144));
    }

    private void AddGuestsButtonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        AddGuestsButton.setBackground(new Color(112,128,144));
    }

    private void AddGuestsButtonMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        AddGuestsButton.setBackground(new Color(60,63,65));

    }

    private void AddGuestsButtonMousePressed(java.awt.event.MouseEvent evt) {
        AddGuestsButton.setBackground(new Color(112,128,144));
    }

    private void AddGuestsButtonMouseReleased(java.awt.event.MouseEvent evt) {
        AddGuestsButton.setBackground(new Color(112,128,144));
    }

    private void EmpleadosLabelbuttonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        employees newframe = new employees();
        newframe.setVisible(true);
        this.dispose();
    }

    private void ReservacionesLabelbuttonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        RoomChecker newframe = new RoomChecker();
        newframe.setVisible(true);
        this.dispose();
    }

    private void AtencionClienteLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Servicio_cliente newframe = new Servicio_cliente();
        newframe.setVisible(true);
        this.dispose();
    }

    private void BuscarLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        MenuBuscar newframe = new MenuBuscar();
        newframe.setVisible(true);
        this.dispose();
    }

    private void AddGuestsButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ReservationsAdd reservationsAdd = new ReservationsAdd();
        reservationsAdd.setVisible(true);
        this.dispose();
    }
    private void CheckRoomsLabelbuttonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        ShowCuartos showCuartos = new ShowCuartos();
        showCuartos.setVisible(true);
        this.dispose();
    }

    private void CheckRoomsLabelbuttonMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        CheckRoomsLabelbutton.setBackground(new Color(112,128,144));

    }

    private void CheckRoomsLabelbuttonMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        CheckRoomsLabelbutton.setBackground(new Color(60,63,65));

    }

    private void CheckRoomsLabelbuttonMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        CheckRoomsLabelbutton.setBackground(new Color(112,128,144));

    }

    private void CheckRoomsLabelbuttonMouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        CheckRoomsLabelbutton.setBackground(new Color(112,128,144));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel AddGuestsButton;
    private javax.swing.JPanel AtencionClienteLabelButton;
    private javax.swing.JPanel BuscarLabelButton;
    private javax.swing.JPanel CheckRoomsLabelbutton;
    private javax.swing.JPanel EmpleadosLabelbutton;
    private javax.swing.JPanel ReservacionesLabelbutton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
